version: '3.8'
services:
{% for container in containers %}
  {{ container.name }}:
    image: rtsp-samsung-tv:1.0.0
    container_name: {{ container.name }}
    environment:
      - SERVER_IP={{ container.serverIp }}
      - WS_PORT={{ container.wsPort }}
    volumes:
      - ./config-files/generated_configs/{{ container.name }}/userChannels.json:/root/.rtsp/userChannels.json
    ports:
      - "{{ container.webPort }}:3004"
      - "{{ container.wsPort }}:9999"
{% endfor %}
